"""Resolve Obsidian wikilinks and inject a Backlinks section for in-vault knowledge graph edges.

Wikilink syntax follows Obsidian: https://obsidian.md/help/links
"""

from __future__ import annotations

import hashlib
import logging
import re
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import TYPE_CHECKING

import yaml

logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from wiki_langgraph.config import Settings

from wiki_langgraph.frontmatter_graph import (
    NOTE_CREATED,
    NOTE_MODIFIED,
    INDEX_KIND_VALUE,
    WG_COMPILED,
    WG_KIND,
    WG_VERSION,
    WikiGraphFrontmatterStats,
    merge_wiki_graph_frontmatter,
    utc_now_iso,
)

# Markers so re-runs replace only our managed blocks (not hand-written sections).
BACKLINKS_BEGIN = "<!-- wiki-langgraph backlinks -->"
BACKLINKS_END = "<!-- /wiki-langgraph backlinks -->"

SEE_ALSO_BEGIN = "<!-- wiki-langgraph see-also -->"
SEE_ALSO_END = "<!-- /wiki-langgraph see-also -->"

SEMANTIC_IN_BEGIN = "<!-- wiki-langgraph semantic-incoming -->"
SEMANTIC_IN_END = "<!-- /wiki-langgraph semantic-incoming -->"


@dataclass(frozen=True)
class IndexNoteEntry:
    relpath: str
    label: str
    created: str | None = None
    modified: str | None = None
    compiled_from: str | None = None
    tags: tuple[str, ...] = ()
    explicit_links: int = 0
    backlinks: int = 0
    semantic_outgoing: int = 0
    semantic_incoming: int = 0


def _strip_managed_block(body: str, begin: str, end: str) -> str:
    """Remove one managed HTML-comment-wrapped block from ``body``."""
    if begin not in body:
        return body.rstrip() + ("\n" if body and not body.endswith("\n") else "")
    before, _, rest = body.partition(begin)
    if end in rest:
        _, _, after = rest.partition(end)
        return (before.rstrip() + "\n" + after.lstrip()).rstrip() + "\n"
    return before.rstrip() + "\n"


def _strip_backlinks_block(body: str) -> str:
    """Remove the backlinks block generated by a previous compile."""
    return _strip_managed_block(body, BACKLINKS_BEGIN, BACKLINKS_END)


def _strip_see_also_block(body: str) -> str:
    """Remove the see-also block generated by a previous compile."""
    return _strip_managed_block(body, SEE_ALSO_BEGIN, SEE_ALSO_END)


def _strip_semantic_incoming_block(body: str) -> str:
    """Remove the semantic-incoming footer from a previous compile."""
    return _strip_managed_block(body, SEMANTIC_IN_BEGIN, SEMANTIC_IN_END)


def _strip_generated_blocks(body: str) -> str:
    """Remove managed blocks (see-also, backlinks, semantic-incoming) for a clean source body."""
    t = _strip_semantic_incoming_block(body)
    t = _strip_backlinks_block(t)
    return _strip_see_also_block(t)


def _managed_block_body(body: str, begin: str, end: str) -> str:
    pattern = re.compile(rf"{re.escape(begin)}\n(.*?){re.escape(end)}", flags=re.DOTALL)
    match = pattern.search(body)
    return match.group(1) if match else ""


def _format_see_also_section(semantic_related: list[str], *, wiki_root: Path | None) -> str:
    """A managed 'See also' block containing real [[wikilinks]] to related notes.

    Unlike the backlinks footer, this section lives in the *body* of the compiled
    wiki note so Obsidian resolves the links and includes them in the forward-link
    graph.  On re-compile the block is stripped and rebuilt.
    """
    if not semantic_related:
        return ""
    links = " · ".join(
        f"[[{_footer_wikilink_label(wiki_root, r)}]]" for r in sorted(semantic_related)
    )
    inner = f"**See also:** {links}"
    return f"\n{SEE_ALSO_BEGIN}\n{inner}\n{SEE_ALSO_END}\n"


def extract_wikilink_targets(markdown: str) -> set[str]:
    """Extract internal link targets from Obsidian ``[[...]]`` (excludes embeds ``![[...]]``).

    Handles ``[[Note]]``, ``[[Note|alias]]``, ``[[Note#Heading]]``, ``[[Note#^block]]``.
    Returns the *link* portion before ``|``, ``#``, or closing ``]]``.
    """
    out: set[str] = set()
    for m in re.finditer(r"\[\[([^\]#|]+)(?:\|[^\]]*)?(?:#[^\]]*)?\]\]", markdown):
        start = m.start()
        if start >= 1 and markdown[start - 1] == "!":
            continue
        out.add(m.group(1).strip())
    return out


def _frontmatter_title(text: str) -> str | None:
    """Return ``title:`` from YAML frontmatter if present."""
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    block = text[3:end]
    for line in block.splitlines():
        if line.lower().startswith("title:"):
            return line.split(":", 1)[1].strip().strip("\"'")
    return None


def _frontmatter_map(text: str) -> dict[str, object]:
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, flags=re.DOTALL)
    if not m:
        return {}
    try:
        data = yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return {}
    if not isinstance(data, dict):
        return {}
    return {str(k): v for k, v in data.items()}


def _normalize_tags_for_index(raw: object) -> tuple[str, ...]:
    if raw is None:
        return ()
    if isinstance(raw, str):
        return tuple(t.strip() for t in raw.split(",") if t.strip())
    if isinstance(raw, list):
        return tuple(str(t).strip() for t in raw if str(t).strip())
    value = str(raw).strip()
    return (value,) if value else ()


def _collect_md_relpaths(raw_root: Path, rel_uris: list[str]) -> list[str]:
    return sorted(p for p in rel_uris if p.lower().endswith(".md"))


def _build_stem_index(md_relpaths: list[str]) -> dict[str, list[str]]:
    stem_map: dict[str, list[str]] = {}
    for rel in md_relpaths:
        stem = PurePosixPath(rel).stem.lower()
        stem_map.setdefault(stem, []).append(rel)
    return stem_map


def resolve_wikilink_target(
    target: str,
    stem_to_paths: dict[str, list[str]],
    title_to_paths: dict[str, list[str]],
    all_md: set[str],
) -> list[str]:
    """Resolve a wikilink target string to one or more ``.md`` posix relpaths.

    If the link looks like ``folder/Note``, match path suffix. Otherwise match
    stem or YAML ``title:``; if ambiguous, return all matches.
    """
    t = target.strip()
    if not t:
        return []
    t_clean = t.removesuffix(".md")
    # Path-style link: treat as suffix of vault-relative path
    if "/" in t_clean:
        suffix = t_clean.lower()
        hits = [p for p in all_md if p.lower().endswith(suffix + ".md") or p.lower() == suffix + ".md"]
        return sorted(hits)

    key = PurePosixPath(t_clean).stem.lower()
    paths = list(stem_to_paths.get(key, []))
    if not paths:
        paths = list(title_to_paths.get(t.lower(), []))
    return sorted(paths)


def wikilink_display_name(md_relpath: str) -> str:
    """Default Obsidian display for ``[[...]]``: path without ``.md`` (slashes allowed)."""
    p = PurePosixPath(md_relpath)
    if p.suffix.lower() == ".md":
        return str(p.with_suffix(""))
    return str(p)


def strip_redundant_wiki_prefix(wiki_root: Path, rel: str) -> str:
    """Drop leading segments of ``rel`` that repeat the end of ``wiki_root``.

    If ``WIKI_DATA_WIKI_DIR`` is ``.../Some Folder/wiki`` and ingest lists
    ``wiki/Note.md`` (because the raw tree mirrors that folder), joining
    ``wiki_root / rel`` would incorrectly produce ``.../wiki/wiki/Note.md``.
    This removes the longest prefix of ``rel`` whose segments match the
    trailing segments of ``wiki_root`` (case-sensitive, posix-style).
    """
    parts = [p for p in PurePosixPath(rel).parts if p]
    if not parts:
        return rel
    w_parts = wiki_root.resolve().parts
    max_k = min(len(parts), len(w_parts))
    best = 0
    for k in range(1, max_k + 1):
        if parts[:k] == list(w_parts[-k:]):
            best = k
    if best == 0:
        return rel
    rest = parts[best:]
    if not rest:
        return rel
    return str(PurePosixPath(*rest))


def _footer_wikilink_label(wiki_root: Path | None, rel: str) -> str:
    """Display name for backlinks/footer when optional wiki root strips duplicates."""
    if wiki_root is None:
        return wikilink_display_name(rel)
    return wikilink_display_name(strip_redundant_wiki_prefix(wiki_root, rel))


def _index_entry_for_note(
    rel: str,
    *,
    wiki_root: Path | None,
    text: str,
    explicit_links: int,
    backlinks: int,
    semantic_outgoing: int,
    semantic_incoming: int,
) -> IndexNoteEntry:
    frontmatter = _frontmatter_map(text)
    return IndexNoteEntry(
        relpath=strip_redundant_wiki_prefix(wiki_root, rel) if wiki_root else rel,
        label=_footer_wikilink_label(wiki_root, rel),
        created=str(frontmatter[NOTE_CREATED]) if frontmatter.get(NOTE_CREATED) is not None else None,
        modified=str(frontmatter[NOTE_MODIFIED]) if frontmatter.get(NOTE_MODIFIED) is not None else None,
        compiled_from=str(frontmatter["compiled_from"]) if frontmatter.get("compiled_from") is not None else None,
        tags=_normalize_tags_for_index(frontmatter.get("tags")),
        explicit_links=explicit_links,
        backlinks=backlinks,
        semantic_outgoing=semantic_outgoing,
        semantic_incoming=semantic_incoming,
    )


def _skip_index_in_index_listing(wiki_root: Path | None, rel: str) -> bool:
    """True if this path is the generated ``Index.md`` (do not list the index in itself)."""
    if wiki_root is None:
        return PurePosixPath(rel).name.lower() == "index.md"
    out = strip_redundant_wiki_prefix(wiki_root, rel)
    return PurePosixPath(out).name.lower() == "index.md"


def dedupe_raw_uris_for_wiki(wiki_root: Path, rel_uris: list[str]) -> list[str]:
    """Keep one ingest path per distinct output file under ``wiki_root``.

    Different raw paths (e.g. ``wiki/a.md`` vs ``Session Summaries/a.md``) can
    normalize to the same wiki path after :func:`strip_redundant_wiki_prefix`;
    without deduping, the same note would be compiled twice and ``Index.md``
    would list duplicate wikilinks.
    """
    by_out: dict[str, str] = {}
    for rel in sorted(rel_uris, key=lambda r: (len(r), r)):
        out_rel = strip_redundant_wiki_prefix(wiki_root, rel)
        key = str((wiki_root / out_rel).resolve())
        if key not in by_out:
            by_out[key] = rel
    return sorted(by_out.values())


def compute_backlinks(
    forward: dict[str, set[str]],
    stem_to_paths: dict[str, list[str]],
    title_to_paths: dict[str, list[str]],
    all_md: set[str],
) -> dict[str, set[str]]:
    """Map each ``.md`` relpath -> set of source ``.md`` relpaths that link to it."""
    back: dict[str, set[str]] = {p: set() for p in all_md}
    for src, targets in forward.items():
        for t in targets:
            for resolved in resolve_wikilink_target(t, stem_to_paths, title_to_paths, all_md):
                if resolved in back and resolved != src:
                    back[resolved].add(src)
    return back


def format_explicit_backlinks_footer(incoming: list[str], *, wiki_root: Path | None = None) -> str:
    """Footer: notes that **authored** a ``[[wikilink]]`` to this page (Obsidian-true backlinks)."""
    if not incoming:
        return ""
    bl = [
        "## Backlinks",
        "",
        "Notes that link here (authored ``[[wikilinks]]``):",
        "",
    ]
    bl.extend(f"- [[{_footer_wikilink_label(wiki_root, rel)}]]" for rel in sorted(incoming))
    inner = "\n".join(bl)
    return f"\n{BACKLINKS_BEGIN}\n{inner}\n\n{BACKLINKS_END}\n"


def format_semantic_incoming_footer(sources: list[str], *, wiki_root: Path | None = None) -> str:
    """Footer: notes whose compile-time \"See also\" suggested this page — **not** authored links."""
    if not sources:
        return ""
    lines = [
        "## Related (semantic)",
        "",
        "_Compile-time suggestions: these notes listed this page in their suggested “See also”. "
        "This is not the same as an authored link to this page (see **Backlinks** above)._",
        "",
    ]
    lines.extend(f"- [[{_footer_wikilink_label(wiki_root, rel)}]]" for rel in sorted(sources))
    inner = "\n".join(lines)
    return f"\n{SEMANTIC_IN_BEGIN}\n{inner}\n\n{SEMANTIC_IN_END}\n"


def format_graph_footer(
    incoming_explicit: list[str],
    incoming_semantic: list[str],
    *,
    wiki_root: Path | None = None,
) -> str:
    """Append both footers: authored **Backlinks** first, then **Related (semantic)** if any.

    Semantic outbound recommendations stay in the **See also** body block
    (:func:`_format_see_also_section`); they are not mixed into the backlinks graph.
    """
    a = format_explicit_backlinks_footer(incoming_explicit, wiki_root=wiki_root)
    b = format_semantic_incoming_footer(incoming_semantic, wiki_root=wiki_root)
    return a + b


def compile_linked_markdown(
    raw_root: Path,
    wiki_root: Path,
    rel_uris: list[str],
    *,
    settings: Settings | None = None,
    content_overrides: dict[str, str] | None = None,
    semantic_cache: dict[str, dict[str, object]] | None = None,
) -> tuple[int, int, int]:
    """Copy/process markdown from ``raw_root`` into ``wiki_root`` and append graph footer.

    Non-``.md`` files are copied verbatim.  Non-``.md`` files and ``.md`` files whose
    final output is byte-identical to the on-disk wiki note are **skipped** (no write, no
    mtime update) so downstream tools don't see spurious changes.

    When ``content_overrides`` is set, keys are posix rel paths; those ``.md`` bodies are taken
    as given (e.g. LLM-authored) instead of reading from ``raw_root`` — used for incremental
    compile.

    ``semantic_cache`` is a mutable dict ``{rel: {"hash": str, "edges": list[str]}}`` loaded
    from the manifest.  Cache hits skip LLM/QMD calls for unchanged notes; misses compute
    and update the dict in-place so the caller can persist it back to the manifest.

    When ``settings.semantic_links`` is set, use ``semantic_backend``:

    - ``llm`` — requires ``openai_api_base``; see :mod:`wiki_langgraph.linking_llm`.
    - ``qmd`` — runs ``qmd query`` per note; see :mod:`wiki_langgraph.linking_qmd`.

    Returns ``(md_files_written, other_files_copied, semantic_edge_count)``.
    """
    md_relpaths = _collect_md_relpaths(raw_root, rel_uris)
    stem_to_paths = _build_stem_index(md_relpaths)
    all_md_set = set(md_relpaths)

    # Read all content (use overrides for LLM-authored notes).
    contents: dict[str, str] = {}
    for rel in md_relpaths:
        if content_overrides is not None and rel in content_overrides:
            text = content_overrides[rel]
        else:
            text = (raw_root / rel).read_text(encoding="utf-8")
        contents[rel] = text

    title_to_paths: dict[str, list[str]] = {}
    for rel in md_relpaths:
        title = _frontmatter_title(contents[rel])
        if title:
            title_to_paths.setdefault(title.lower(), []).append(rel)

    backend = "llm"
    if settings is not None:
        backend = getattr(settings, "semantic_backend", "llm") or "llm"
    use_semantic_llm = bool(
        settings is not None
        and getattr(settings, "semantic_links", False)
        and backend == "llm"
        and getattr(settings, "openai_api_base", None)
    )
    use_semantic_qmd = bool(
        settings is not None
        and getattr(settings, "semantic_links", False)
        and backend == "qmd"
    )

    # ── Pass 1: pre-compute ALL semantic edges before backlink computation ──────
    # This is the key design: semantic discovery informs the graph on the SAME
    # compile run, so new notes with no hand-written [[wikilinks]] still get
    # edges injected and their related notes get real backlinks immediately.
    all_semantic: dict[str, list[str]] = {}
    semantic_cache_hits = 0

    if use_semantic_llm or use_semantic_qmd:
        for rel in md_relpaths:
            base_for_sem = _strip_generated_blocks(contents[rel])
            body_hash = hashlib.sha256(base_for_sem.encode()).hexdigest()
            cached = semantic_cache.get(rel) if semantic_cache is not None else None
            if cached is not None and cached.get("hash") == body_hash:
                all_semantic[rel] = list(cached.get("edges") or [])
                semantic_cache_hits += 1
            else:
                if use_semantic_llm:
                    from wiki_langgraph.linking_llm import suggest_semantic_related
                    all_semantic[rel] = suggest_semantic_related(settings, rel, base_for_sem, md_relpaths)
                else:
                    from wiki_langgraph.linking_qmd import suggest_related_via_qmd
                    all_semantic[rel] = suggest_related_via_qmd(settings, rel, base_for_sem, md_relpaths)
                if semantic_cache is not None:
                    semantic_cache[rel] = {"hash": body_hash, "edges": all_semantic[rel]}

    # ── Forward graph: authored [[wikilinks]] only (provenance for Backlinks footer) ─
    # Semantic similarity is handled separately: See also (outbound) + Related (semantic)
    # (inbound). Mixing semantic stems into the same graph as wikilinks would make
    # generated backlinks look like Obsidian-true authored links.
    forward_explicit: dict[str, set[str]] = {}
    for rel in md_relpaths:
        forward_explicit[rel] = extract_wikilink_targets(contents[rel])

    backlinks_explicit = compute_backlinks(
        forward_explicit, stem_to_paths, title_to_paths, all_md_set
    )

    # Inbound semantic: target_rel had src in its suggested list (all_semantic[src]).
    semantic_incoming: dict[str, set[str]] = {p: set() for p in all_md_set}
    for src, sem_rels in all_semantic.items():
        for target_rel in sem_rels:
            if target_rel in all_md_set and target_rel != src:
                semantic_incoming[target_rel].add(src)

    # ── Pass 2: write wiki files ────────────────────────────────────────────────
    md_written = 0
    md_skipped = 0
    other_copied = 0
    semantic_edges = sum(len(v) for v in all_semantic.values())
    compiled_at_iso = utc_now_iso()

    for rel in rel_uris:
        raw_path = raw_root / rel
        out_rel = strip_redundant_wiki_prefix(wiki_root, rel)
        wiki_path = wiki_root / out_rel
        wiki_path.parent.mkdir(parents=True, exist_ok=True)

        if not rel.lower().endswith(".md"):
            new_bytes = raw_path.read_bytes()
            if wiki_path.is_file() and wiki_path.read_bytes() == new_bytes:
                continue
            wiki_path.write_bytes(new_bytes)
            other_copied += 1
            continue

        base = _strip_generated_blocks(contents[rel])
        sem_for_rel = all_semantic.get(rel)
        existing_frontmatter = _frontmatter_map(base)
        authored_body_targets = {
            resolved
            for target in extract_wikilink_targets(base)
            for resolved in resolve_wikilink_target(target, stem_to_paths, title_to_paths, all_md_set)
        }

        graph_stats = WikiGraphFrontmatterStats(
            compiled_at_iso=compiled_at_iso,
            created_at_iso=(compiled_at_iso if existing_frontmatter.get(NOTE_CREATED) is None else None),
        )
        base = merge_wiki_graph_frontmatter(base, stats=graph_stats)

        # Inject "See also" wikilinks into the body so Obsidian traverses them.
        see_also_targets = [
            target_rel for target_rel in (sem_for_rel or []) if target_rel not in authored_body_targets
        ]
        see_also = _format_see_also_section(see_also_targets, wiki_root=wiki_root)

        # Dedupe: omit from **Related (semantic)** if that note is already our outbound See also
        # target (same page would list them twice).
        outgoing_sem = set(see_also_targets)
        inc_explicit = sorted(backlinks_explicit.get(rel, set()))
        sem_raw = (semantic_incoming.get(rel, set()) or set()) - set(
            backlinks_explicit.get(rel, set())
        )
        inc_semantic = sorted(sem_raw - outgoing_sem)
        footer = format_graph_footer(
            inc_explicit, inc_semantic, wiki_root=wiki_root
        )
        body = base.rstrip() + see_also + footer
        body_bytes = body.encode("utf-8")
        if wiki_path.is_file() and wiki_path.read_bytes() == body_bytes:
            md_skipped += 1
            continue
        wiki_path.write_text(body, encoding="utf-8")
        md_written += 1

    if md_skipped or semantic_cache_hits:
        logger.debug(
            "compile: skipped %d identical md write(s), %d semantic cache hit(s)",
            md_skipped,
            semantic_cache_hits,
        )

    return md_written, other_copied, semantic_edges


def build_index_entries(
    raw_root: Path,
    wiki_root: Path,
    rel_uris: list[str],
) -> list[IndexNoteEntry]:
    md_relpaths = _collect_md_relpaths(raw_root, rel_uris)
    contents: dict[str, str] = {}
    for rel in md_relpaths:
        out_rel = strip_redundant_wiki_prefix(wiki_root, rel)
        wiki_path = wiki_root / out_rel
        if not wiki_path.is_file():
            continue
        contents[rel] = wiki_path.read_text(encoding="utf-8")

    all_md_set = set(contents)
    stem_to_paths = _build_stem_index(list(contents))
    title_to_paths: dict[str, list[str]] = {}
    for rel, text in contents.items():
        title = _frontmatter_title(text)
        if title:
            title_to_paths.setdefault(title.lower(), []).append(rel)

    forward_explicit = {
        rel: extract_wikilink_targets(_strip_generated_blocks(text)) for rel, text in contents.items()
    }
    backlinks_explicit = compute_backlinks(forward_explicit, stem_to_paths, title_to_paths, all_md_set)

    semantic_outgoing: dict[str, list[str]] = {}
    semantic_incoming: dict[str, set[str]] = {p: set() for p in all_md_set}
    for rel, text in contents.items():
        see_also_targets = extract_wikilink_targets(_managed_block_body(text, SEE_ALSO_BEGIN, SEE_ALSO_END))
        outgoing: list[str] = []
        for target in see_also_targets:
            for resolved in resolve_wikilink_target(target, stem_to_paths, title_to_paths, all_md_set):
                if resolved != rel and resolved not in outgoing:
                    outgoing.append(resolved)
        semantic_outgoing[rel] = outgoing

        incoming_targets = extract_wikilink_targets(_managed_block_body(text, SEMANTIC_IN_BEGIN, SEMANTIC_IN_END))
        for target in incoming_targets:
            for resolved in resolve_wikilink_target(target, stem_to_paths, title_to_paths, all_md_set):
                if resolved != rel:
                    semantic_incoming[rel].add(resolved)

    return [
        _index_entry_for_note(
            rel,
            wiki_root=wiki_root,
            text=contents[rel],
            explicit_links=len(forward_explicit.get(rel, set())),
            backlinks=len(backlinks_explicit.get(rel, set())),
            semantic_outgoing=len(semantic_outgoing.get(rel, [])),
            semantic_incoming=len(semantic_incoming.get(rel, set())),
        )
        for rel in sorted(contents)
    ]


def format_index_markdown(
    md_relpaths: list[str],
    *,
    wiki_root: Path | None = None,
    entries: list[IndexNoteEntry] | None = None,
) -> str:
    """``Index.md`` registry with wikilinks and compact note metadata."""
    lines = [
        "---",
        "title: Wiki Index",
        "tags:",
        "  - generated",
        "  - index",
        f"{WG_VERSION}: 1",
        f"{WG_KIND}: {INDEX_KIND_VALUE}",
        f"{WG_COMPILED}: {utc_now_iso()}",
        "---",
        "",
        "# Index",
        "",
        "Compiled notes (wikilinks per [Obsidian help](https://obsidian.md/help/links)):",
        "",
    ]
    if not md_relpaths:
        lines.append("_No markdown sources._")
    elif entries:
        lines.extend(
            [
                "Generated note registry with stable wikilinks and compact metadata for navigation and agent discovery.",
                "",
                "## Notes",
                "",
            ]
        )
        seen_labels: set[str] = set()
        for entry in sorted(entries, key=lambda item: item.label.lower()):
            if entry.label in seen_labels:
                continue
            seen_labels.add(entry.label)
            lines.append(f"### [[{entry.label}]]")
            lines.append(f"- path: `{entry.relpath}`")
            if entry.created:
                lines.append(f"- created: `{entry.created}`")
            if entry.modified:
                lines.append(f"- modified: `{entry.modified}`")
            if entry.compiled_from:
                lines.append(f"- source: `{entry.compiled_from}`")
            if entry.tags:
                lines.append("- tags: " + ", ".join(f"`{tag}`" for tag in entry.tags))
            lines.append(f"- explicit_links: {entry.explicit_links}")
            lines.append(f"- backlinks: {entry.backlinks}")
            lines.append(f"- semantic_outgoing: {entry.semantic_outgoing}")
            lines.append(f"- semantic_incoming: {entry.semantic_incoming}")
            lines.append("")
    else:
        seen_labels: set[str] = set()
        for rel in sorted(md_relpaths):
            if _skip_index_in_index_listing(wiki_root, rel):
                continue
            label = _footer_wikilink_label(wiki_root, rel)
            if label in seen_labels:
                continue
            seen_labels.add(label)
            lines.append(f"- [[{label}]]")
    lines.append("")
    return "\n".join(lines)
